config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
     sessions: 'users/sessions'
   }


  root to: "homepage#index"
  resources :homepage

  resources :users

  resources :locations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
      resources :users_locations
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users
      resources :locations do
        collection do
          post :yelp_api_search
        end
      end
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, uniqueness: { message: "Username is already in use" }
  validates :name, presence: true

  has_many :user_locations
  has_many :locations, through: :user_locations
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  skip_before_filter :verify_authenticity_token







end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.all
  end

  def show
    @user = current_user
    @user_location = UserLocation.all
    @locations = current_user.locations
    coordinates = @user.locations.map do |cord|
      {lat: cord["latitude"], long: cord["longitude"], name: cord["name"], url: cord["url"], address: cord["address"]}
    end
    @coordinates = JSON.unparse(coordinates)
  end


end

app/views/users/index.html.erb
<h1> Work in progress </h1>



<%  @user.each do |i| %>

<p>   Name: <%= i.name %>    </p>

<% end %>

app/views/users/show.html.erb
<div class="sky">
<html>
  <head>
    <style>
      #map {
        height: 400px;
        width: 75%;
        border-style: solid;
        border-color: black;
        border-radius: 10px;
       }
    </style>
  </head>
  <body>
    <br/>
    <h1> <p class="title-profile"> Discover <i class="fa fa-cloud icon-cloud" aria-hidden="true" style="color:LightSkyBlue"></i> </p> </h1>
      <div class=large-offset-2 large-9 centered columns>
        <div id="map"></div>
      </div>
    <script>

    function initMap() {
      var boston = {lat: 42.364506, lng: -71.038887};
      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 12,
        center: boston
      });

      var cords = <%= @coordinates.html_safe %>
      for( var i = 0; i < cords.length; i++){
        var latLng = new google.maps.LatLng(cords[i].lat, cords[i].long);
        let marker = new google.maps.Marker({
          position: latLng,
          animation: google.maps.Animation.DROP,
          map: map
        });


        var message = `${cords[i].name}`;
        var url = `${cords[i].url}`;
        var address = `${cords[i].address}`;
        function addInfoWindow(marker, message) {

            var infoWindow = new google.maps.InfoWindow({
                content: `<p>${message}</p>` + `<p>${address}</p>` + `<p><a href="${url}"/>Learn More</p>`
            });

            google.maps.event.addListener(marker, 'click', function () {
                infoWindow.open(map, marker);
            });
        }



        marker.addListener('click', addInfoWindow(marker, message));
      }
    }

    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['API_KEY']%>&callback=initMap">
    </script>
  </body>
</html>


<br/>
<br/>



      <% @locations.each do |item| %>
      <% @hey = "" %>
      <% if @user_location.find_by(user_id: current_user["id"], location_id: item.id).favorite == true %>
      <% @hey = "\u{2764}"%>
      <% end  %>
      <div class="small-4 columns">
        <div class="items_profile">
            <div id="heart"><p> <%= @hey %> </p></div>
            <div class="box1"><img src="<%=item['cover_url']%>"/></div>
              <h4><div class="title_name"><%=item['name'] %></div></h4>
              <div class="delete"><%= button_to 'Delete',  location_path(user_id: @user.id, location_id: item.id), method: :delete %></div>  <div class="favorite"><%=button_to "Favorite", location_path(@user.id, location_id: item.id), method: :put %></div>

              <br/>
        </div>
      </div>

<% end  %>
</div>