config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
     sessions: 'users/sessions'
   }


  root to: "homepage#index"
  resources :homepage

  resources :users

  resources :locations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
      resources :users_locations
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users
      resources :locations do
        collection do
          post :yelp_api_search
        end
      end
    end
  end

end

app/views/layouts/_footer.html.erb
<footer class="homepage-footer">
  <div class="row">
    <div class="small-12 columns">
      <p class="title"> Discover <i class="fa fa-cloud" aria-hidden="true" style="color:LightSkyBlue"></i> </p>
      <p class="icons">
        <a href="mailto:hojo1025@gmail.com">
          <i class="fa fa-envelope-o" aria-hidden="true"></i>
        </a> <a>|</a>

        <a href="https://www.linkedin.com/in/josh-ho">
          <i class="fa fa-linkedin" aria-hidden="true"></i>
        </a> <a>|</a>

        <a href="https://github.com/joshh45">
          <i class="fa fa-github" aria-hidden="true"></i>
        </a>
      </p>


      <!-- <p class="copyright"> Copyright &copy;2017 Josh Ho </p> -->
    </div>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
  <div class="title-bar large-12 columns small-12 columns medium-12 columns" id = 'title' data-sticky data-options="marginTop:0;" style="width:100%" data-top-anchor="1" >



    <div class="title-bar-right">
      <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong> |
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </div>

  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />



    <title><%= content_for?(:title) ? yield(:title) : "Discover" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Allerta+Stencil" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">








  <!-- <ul class="nav">
<li class="active"><a href="/ideas">Ideas</a></li>
</ul> -->

<!-- <% if notice %>
<p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
<p class="alert alert-danger"><%= alert %></p>
<% end %> -->


  <body>
    <%= render 'layouts/navigation' %>
    <div class= "large-12 medium-12 small-12">
      <p class="navbar-text pull-middle">

      <% if user_signed_in? %>
       <div class="nav_buttons">
        <%= link_to 'Home', homepage_index_path %> |
        <%= link_to 'Profile', user_path(current_user) %> |
        <%= link_to 'Discover', locations_path %>
      </div>
      <% else %>
        <div class="nav_buttons">
          <div class="row">

          </div>
        </div>
      <% end %>
    </div>
    <%= yield %>
  </body>

</html>